# Generated by Django 5.1.1 on 2024-10-17 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_remove_producto_imagen_imagenproducto'),
        ('Ventas', '0003_producto_alter_detalleventa_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
