# Generated by Django 5.1.1 on 2024-10-17 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_remove_producto_imagen_imagenproducto'),
        ('Ventas', '0007_producto_subcategoria_remove_detalleventa_venta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='subcategoria',
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
