# Generated by Django 5.1.2 on 2024-10-26 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_added',)},
        ),
    ]
